### PR TITLE
8.0 dot files

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by dreispt** [comment]
@mileo Please enable the CI checks on the repo at https://travis-ci.org/kmee/project-agile

**Comment by mileo** [comment]
Done.

**Comment by dreispt** [comment]
What I did was a quick hack, to give me time to work on MQT.
The Travis log already has a valuable list of lint issues: 
https://travis-ci.org/kmee/project-agile/jobs/151176311#L2212

And also the code coverage detailed report:
https://travis-ci.org/kmee/project-agile/jobs/151176314#L3048

**Comment by mileo** [comment]
Can i help you fixing test_flake8/test_pylint errors?

**Comment by dreispt** [comment]
I'm sorry, I wont be able to spend time on that in the next weeks.

**Comment by dreispt** [comment]
Fell free to fix or improve whatever you like - it's still your repo.
IMO if you are able to use pull requests even the better, since it's easier to discuss and provide feedback that way.

**Pull request merged**
